services:
  karma_chat:
    build:
      dockerfile: Docker/Dockerfile
    ports:
      - "3030:3030"
    command: cargo watch -x 'run'
    volumes:
      - ./applications/karma-chat:/work:delegated

